### ISSUE TITLE
this didnt work for me 

### ISSUE THREAD

**Issue by dairdevil0420** [Morsmalleo/TheFatRat-MinGW-fix#2]
![Screenshot_2022-08-27_08-24-40](https://user-images.githubusercontent.com/111643629/187036750-604661a7-5f04-4255-9036-786754a0c025.png)
im at a dead end. any advice?

**Comment by Morsmalleo** [comment]
That's a new one on me, what's your OS?

**Comment by dairdevil0420** [comment]
Xubuntu 22.04 I ended up tinkering with the repositories in the “software&updates” app and disabled the Debian one cuz it was having the constant error of having no release file which was halting and apt update/ upgrade commands and it fixed the problem

**Comment by Morsmalleo** [comment]
> Xubuntu 22.04 I ended up tinkering with the repositories in the “software&updates” app and disabled the Debian one cuz it was having the constant error of having no release file which was halting any apt update/ upgrade commands and it fixed the problem

The Debian software Repo is needed for the correct installation of mingw, not sure why it was failing could have been a recent push that was made, I'll retest the script today, and see if I face the same problem

**Comment by dairdevil0420** [comment]
wierd cuz it didnt work till i disabled it tho

**Comment by Morsmalleo** [comment]
> wierd cuz it didnt work till i disabled it tho

Very weird... Did it install the correct versions of mingw for you?? Run `chk_tools` inside *TheFatRat* to confirm this.
